ALTER TABLE Records ADD Status NVARCHAR(50) NULL;
ALTER TABLE Records ADD Content NVARCHAR(MAX) NULL;
ALTER TABLE Records ADD CreatedAt DATETIME2 NULL;
ALTER TABLE Records ADD CreatedByUserId INT NULL;
ALTER TABLE Records ADD FeedbackText NVARCHAR(MAX) NULL;
ALTER TABLE Records ADD RecordType NVARCHAR(50) NULL;